# List of Enemies to go against

DEFEATED = []
CHALLENGED = []

ENEMIES = (
    "Lucifer",
    "Lot",
    "Jacob",
    "Esau",
    "Bathsheba",
    "Delilah",
    "Joab",
    "James",
    "Judas",
    "Isaiah",
    "Daniel",
    "Xerxes",
    "Jeremiah",
    "Nehemiah",
    "Job",
    "Elihu",
    "Uriah",
    "Dorcas",
    "Rhoda",
    "Elisha",
    "Jezebel",
    "Ahab",
    "Amnon",
    "Tamar",
    "Absalom",
    "Nathan",
    "Boaz",
    "Ruth",
    "Joseph",
    "Simeon",
    "Benjamin",
    "Nebuchadnezzar",
    "Methusaleh",
    "Mary",
    "Mary Magdalene",
    "Abraham",
    "Sarah",
    "Rebekah",
    "Rahab",
    "Joshua",
    "Adam",
    "Eve",
    "Satan",
    "Gabriel",
    "Hosea",
    "Gomer",
    "Ezekiel",
    "Matthew",
    "Solomon",
    "Joash",
    "Aaron",
    "Miriam",
    "Potiphar",
    "Isaac",
    "Noah",
    "Ham",
    "Shem",
    "Japheth",
    "Zechariah",
    "John the Baptist",
    "Hezekiah",
    "Paul",
    "Saul",
    "Esther",
    "Mordecai",
    "Darius",
    "Shadrach",
    "Meshach",
    "Abednego",
    "Jeroboam",
    "Rehoboam",
    "Samuel",
    "Samson",
    "Barak",
    "Balaam",
    "Herod",
    "Martha",
    "Lazarus",
    "Zacheus"
)

POKEDEX = {
    "Lucifer": "a beautiful fallen angel",
    "Lot": "nephew of Abraham",
    "Jacob": "wrestled with God",
    "Esau": "father of Edom",
    "Bathsheba": "mother of Solomon",
    "Delilah": "killer of men",
    "Joab": "killer of men",
    "James": "brother of Jesus",
    "Judas": "betrayer of Jesus",
    "Isaiah": "a great prophet",
    "Daniel": "exile prophet",
    "Xerxes": "king to Esther",
    "Jeremiah": "author of Lamentations",
    "Nehemiah": "builder of walls",
    "Job": "afflicted",
    "Elihu": "friend of Job",
    "Uriah": "I just feel bad for this guy",
    "Dorcas": "friend to the poor",
    "Rhoda": "daughter of the gospel",
    "Elisha": "apprentice to Elijah",
    "Jezebel": "wicked queen",
    "Ahab": "foolish king",
    "Amnon": "bad dude",
    "Tamar": "I just feel bad for her",
    "Absalom": "foolish prince",
    "Nathan": "David's conscience",
    "Boaz": "husband to Ruth",
    "Ruth": "awesome convert",
    "Joseph": "great visionary",
    "Simeon": "mean brother to Joseph",
    "Benjamin": "younger brother to Joseph",
    "Nebuchadnezzar": "King of Babylon",
    "Methusaleh": "oldest man",
    "Mary": "mother of Jesus",
    "Mary Magdalene": "forgiven",
    "Abraham": "father of a nation",
    "Sarah": "wife to Abraham",
    "Rebekah": "mother of Jacob and Esau",
    "Rahab": "Jericho convert",
    "Joshua": "apprentice to Moses",
    "Adam": "first man",
    "Eve": "first woman",
    "Satan": "the dark side",
    "Gabriel": "angel of light",
    "Hosea": "faithful prophet",
    "Gomer": "not a good wife",
    "Ezekiel": "saw God",
    "Matthew": "tax collector disciple",
    "Solomon": "wisest man with a past",
    "Joash": "young king, tragic backstory",
    "Aaron": "first Israel priest",
    "Miriam": "sister of Moses",
    "Potiphar": "believed his wife",
    "Isaac": "the prophesied son",
    "Noah": "built an ark",
    "Ham": "cursed son of Noah",
    "Shem": "son of Noah",
    "Japheth": "son of Noah",
    "Zechariah": "father of John the Baptist",
    "John the Baptist": "the new coming of Isaiah",
    "Hezekiah": "asked for more life... got 15 years",
    "Paul": "brought people to Christ",
    "Saul": "killed followers of Christ",
    "Esther": "the most beautiful queen",
    "Mordecai": "uncle of Esther",
    "Darius": "sent Daniel to the lions den",
    "Shadrach": "friend of Daniel",
    "Meshach": "friend of Daniel",
    "Abednego": "friend of Daniel",
    "Jeroboam": "could've had the kingdom",
    "Rehoboam": "listened to young ones instead of the wiser elders",
    "Samuel": "told off the priest",
    "Samson": "the strongest man but wasted potential",
    "Barak": "fought alongside Deborah",
    "Balaam": "talked to a donkey",
    "Herod": "tried to kill Jesus",
    "Martha": "sister to Lazarus",
    "Lazarus": "raised from the dead",
    "Zacheus": "climbed a tree to talk to Jesus"
}
